version: '2.1'

services:
  coredns-gslb:
    image: coredns-gslb:0.0.1
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 1053:53
      - 1053:53/udp
    volumes:
      - .:/app